// client/src/components/InfoPanel.jsx
import { useEffect, useState } from 'react';
import { aqiInfo, POLLUTANT_LABELS } from '../utils/aqi';
import { safeOutdoorTime, bestHourAdvice, maskAdvice, POLLUTANT_EFFECTS, SOURCE_TAGS } from '../utils/health';

const S = {
  panel: {
    position: 'fixed', right: 24, top: '50%', transform: 'translateY(-50%)',
    width: 260, maxHeight: '88vh', overflowY: 'auto',
    background: 'rgba(2,5,16,0.95)', border: '1px solid #0d2a4a',
    borderRadius: 2, padding: '20px 18px', zIndex: 20,
    fontFamily: "'Courier New', monospace", color: '#8ba4c8',
    scrollbarWidth: 'none',
  },
  sectionLabel: { fontSize: 9, letterSpacing: '0.35em', color: '#2a4a6a', textTransform: 'uppercase', marginBottom: 10 },
  divider:      { border: 'none', borderTop: '1px solid #0a1e38', margin: '14px 0' },
  row:          { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', fontSize: 11, marginBottom: 8, color: '#3a5a7a' },
  val:          { color: '#8ba4c8', letterSpacing: '0.05em', textAlign: 'right', maxWidth: 130 },
  close:        { position: 'absolute', top: 10, right: 12, cursor: 'pointer', fontSize: 13, color: '#2a4a6a' },
};

export default function InfoPanel({ countryCode, onClose }) {
  const [detail,  setDetail]  = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!countryCode) return;
    setLoading(true); setDetail(null); setHistory([]);
    Promise.all([
      fetch(`/api/aqi/country/${countryCode}`).then(r => r.json()),
      fetch(`/api/aqi/history/${countryCode}`).then(r => r.json()),
    ]).then(([d, h]) => {
      setDetail(d);
      setHistory(h.history || []);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, [countryCode]);

  if (!countryCode) return null;

  const aqi       = detail?.avgAqi ?? detail?.aqi;
  const info      = aqi != null ? aqiInfo(aqi) : null;
  const dom       = detail?.dominentpol;
  const polEff    = dom && POLLUTANT_EFFECTS[dom];
  const sourceTag = dom && SOURCE_TAGS[dom];
  const safeTime  = safeOutdoorTime(aqi);
  const bestHour  = bestHourAdvice(aqi, dom);
  const mask      = maskAdvice(aqi);
  const trend     = detail?.trend;
  const spark     = history.slice(-12);
  const maxV      = Math.max(...spark.map(s => s.aqi), 1);
  const SW = 210, SH = 38;
  const preds     = trend?.predictions?.slice(0, 8) ?? [];

  return (
    <div style={{ ...S.panel, borderLeft: `2px solid ${info?.col || '#0d2a4a'}` }}>
      <span style={S.close} onClick={onClose}>✕</span>

      <div style={S.sectionLabel}>Selected Region</div>
      {loading && <div style={{ color: '#2a4a6a', fontSize: 11, letterSpacing: '0.2em' }}>Loading...</div>}

      {detail && info && <>
        <div style={{ fontSize: 14, color: '#c8d8f0', fontWeight: 'bold', marginBottom: 2, letterSpacing: '0.06em' }}>
          {detail.countryName || detail.name}
        </div>
        {detail.city && <div style={{ fontSize: 9, color: '#1a3a5a', marginBottom: 10, letterSpacing: '0.15em' }}>{detail.city}</div>}

        {/* AQI + trend arrow */}
        <div style={{ display: 'flex', alignItems: 'flex-end', gap: 10, marginBottom: 4 }}>
          <div style={{ fontSize: 56, fontWeight: 'bold', lineHeight: 1, color: info.col }}>{aqi}</div>
          {trend && (
            <div style={{ paddingBottom: 8 }}>
              <div style={{ fontSize: 22, color: trend.trend.color }}>{trend.trend.arrow}</div>
              <div style={{ fontSize: 9, color: trend.trend.color, letterSpacing: '0.12em', marginTop: 2 }}>{trend.trend.label}</div>
            </div>
          )}
        </div>
        <div style={{ fontSize: 10, letterSpacing: '0.2em', color: info.col, textTransform: 'uppercase', marginBottom: 4 }}>{info.cat}</div>
        {sourceTag && <div style={{ fontSize: 10, color: '#3a5a7a', marginBottom: 14 }}>{sourceTag.icon} {sourceTag.tag}</div>}

        {/* Sparkline + forecast */}
        {spark.length > 1 && <>
          <hr style={S.divider} />
          <div style={S.sectionLabel}>History + 6h Forecast</div>
          <svg width={SW} height={SH} style={{ display: 'block', marginBottom: 8 }}>
            <polyline
              points={spark.map((s, i) => `${(i / (spark.length - 1)) * (SW * 0.65)},${SH - (s.aqi / maxV) * (SH - 4) - 2}`).join(' ')}
              fill="none" stroke={info.col} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"
            />
            {preds.length > 0 && (
              <polyline
                points={preds.map((v, i) => {
                  const x = SW * 0.65 + (i / (preds.length - 1)) * (SW * 0.32);
                  const y = SH - (v / maxV) * (SH - 4) - 2;
                  return `${x},${y}`;
                }).join(' ')}
                fill="none" stroke={info.col} strokeWidth="1" strokeDasharray="3 3" opacity="0.6"
              />
            )}
            <line x1={SW * 0.65} y1={0} x2={SW * 0.65} y2={SH} stroke="#0d2a4a" strokeWidth="1" strokeDasharray="2 2" />
            <text x={SW * 0.67} y={9} style={{ fontSize: 7, fill: '#1a3a5a', fontFamily: 'monospace' }}>forecast →</text>
          </svg>

          {trend && (
            <div style={{ display: 'flex', gap: 8, marginBottom: 14 }}>
              {[['1h', trend.predictedIn1h], ['3h', trend.predictedIn3h], ['6h', trend.predictedIn6h]].map(([lbl, val]) => (
                <div key={lbl} style={{ flex: 1, background: '#070f22', borderRadius: 2, padding: '6px 0', textAlign: 'center' }}>
                  <div style={{ fontSize: 9, color: '#1a3a5a', letterSpacing: '0.12em' }}>{lbl}</div>
                  <div style={{ fontSize: 16, fontWeight: 'bold', color: aqiInfo(val).col }}>{val}</div>
                </div>
              ))}
            </div>
          )}
        </>}

        {/* Health dashboard */}
        <hr style={S.divider} />
        <div style={S.sectionLabel}>Health Advisory</div>
        <div style={S.row}>Healthy adults<span style={S.val}>{safeTime.healthy}</span></div>
        <div style={S.row}>Sensitive groups<span style={S.val}>{safeTime.sensitive}</span></div>
        <div style={S.row}>Children / Elderly
          <span style={{ ...S.val, color: safeTime.children === 'Stay in' ? '#ff0000' : '#8ba4c8' }}>{safeTime.children}</span>
        </div>
        <div style={S.row}>Best time outside<span style={{ ...S.val, fontSize: 10 }}>{bestHour}</span></div>
        <div style={S.row}>Mask
          <span style={{ ...S.val, color: mask.needed ? '#ff7e00' : '#00e400' }}>{mask.type}</span>
        </div>
        {mask.needed && <div style={{ fontSize: 10, color: '#ff7e00', marginBottom: 8, textAlign: 'right' }}>{mask.note}</div>}

        {/* Pollutant readings */}
        <hr style={S.divider} />
        <div style={S.sectionLabel}>Pollutant Readings</div>
        {detail.iaqi && Object.entries(POLLUTANT_LABELS).map(([key, label]) => {
          const val = detail.iaqi?.[key];
          if (val === null || val === undefined) return null;
          return (
            <div key={key} style={S.row}>
              {label}
              <span style={{ ...S.val, color: dom === key ? info.col : '#8ba4c8' }}>
                {typeof val === 'number' ? val.toFixed(1) : val}
                {key === 'pm25' || key === 'pm10' ? ' μg/m³' : ' ppb'}
                {dom === key && ' ●'}
              </span>
            </div>
          );
        })}

        {/* Dominant pollutant effect card */}
        {polEff && <>
          <hr style={S.divider} />
          <div style={S.sectionLabel}>Primary Concern</div>
          <div style={{ background: '#070f22', borderRadius: 2, padding: '10px 12px', borderLeft: `2px solid ${polEff.color}` }}>
            <div style={{ fontSize: 11, color: polEff.color, fontWeight: 'bold', marginBottom: 4 }}>{polEff.label}</div>
            <div style={{ fontSize: 10, color: '#3a5a7a', marginBottom: 4 }}>Source: {polEff.source}</div>
            <div style={{ fontSize: 10, color: '#5a7a9a', lineHeight: 1.6 }}>{polEff.effect}</div>
          </div>
        </>}

        <hr style={S.divider} />
        <div style={{ fontSize: 10, color: '#3a5a7a', lineHeight: 1.7 }}>{info.advice}</div>

        {detail.baseline30 && (
          <div style={{ marginTop: 12, fontSize: 10, color: '#1a3a5a' }}>
            30-day avg: <span style={{ color: aqiInfo(detail.baseline30).col }}>{detail.baseline30}</span>
            {aqi > detail.baseline30 * 1.5 && <span style={{ color: '#ff7e00' }}> ↑ above normal</span>}
            {aqi < detail.baseline30 * 0.7 && <span style={{ color: '#00e400' }}> ↓ better than usual</span>}
          </div>
        )}
      </>}
    </div>
  );
}

// client-ng/src/app/components/info-panel/info-panel.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { forkJoin } from 'rxjs';
import { AqiService } from '../../services/aqi.service';
import { aqiInfo, POLLUTANT_LABELS } from '../../utils/aqi';
import { safeOutdoorTime, bestHourAdvice, maskAdvice, POLLUTANT_EFFECTS, SOURCE_TAGS } from '../../utils/health';

@Component({
  selector: 'app-info-panel',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './info-panel.component.html',
  styleUrls: ['./info-panel.component.css'],
})
export class InfoPanelComponent implements OnChanges {
  @Input() countryCode: string | null = null;
  @Output() closePanel = new EventEmitter<void>();

  detail: any = null;
  history: any[] = [];
  loading = false;

  readonly POLLUTANT_LABELS = POLLUTANT_LABELS;
  readonly POLLUTANT_EFFECTS = POLLUTANT_EFFECTS;
  readonly SOURCE_TAGS = SOURCE_TAGS;

  constructor(private aqiSvc: AqiService) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['countryCode'] && this.countryCode) {
      this.loading = true;
      this.detail = null;
      this.history = [];
      forkJoin([
        this.aqiSvc.getCountry(this.countryCode),
        this.aqiSvc.getHistory(this.countryCode),
      ]).subscribe({
        next: ([d, h]) => {
          this.detail = d;
          this.history = h.history || [];
          this.loading = false;
        },
        error: () => { this.loading = false; }
      });
    }
  }

  get aqiValue(): number | null { return this.detail?.avgAqi ?? this.detail?.aqi ?? null; }
  get info()  { return this.aqiValue != null ? aqiInfo(this.aqiValue) : null; }
  get dom()   { return this.detail?.dominentpol; }
  get polEff(){ return this.dom && this.POLLUTANT_EFFECTS[this.dom]; }
  get srcTag(){ return this.dom && this.SOURCE_TAGS[this.dom]; }
  get safeTime() { return safeOutdoorTime(this.aqiValue ?? undefined); }
  get bestHour() { return bestHourAdvice(this.aqiValue ?? undefined, this.dom); }
  get mask()     { return maskAdvice(this.aqiValue ?? undefined); }
  get trend()    { return this.detail?.trend; }
  get spark()    { return this.history.slice(-12); }
  get maxV()     { return Math.max(...this.spark.map((s: any) => s.aqi), 1); }
  get preds()    { return this.trend?.predictions?.slice(0, 8) ?? []; }
  readonly SW = 210;
  readonly SH = 38;

  sparkPoints(): string {
    return this.spark.map((s: any, i: number) =>
      `${(i / (this.spark.length - 1)) * (this.SW * 0.65)},${this.SH - (s.aqi / this.maxV) * (this.SH - 4) - 2}`
    ).join(' ');
  }

  forecastPoints(): string {
    return this.preds.map((v: number, i: number) => {
      const x = this.SW * 0.65 + (i / (this.preds.length - 1)) * (this.SW * 0.32);
      const y = this.SH - (v / this.maxV) * (this.SH - 4) - 2;
      return `${x},${y}`;
    }).join(' ');
  }

  pollutantEntries(): { key: string; label: string; val: any }[] {
    if (!this.detail?.iaqi) return [];
    return Object.entries(POLLUTANT_LABELS)
      .map(([key, label]) => ({ key, label, val: this.detail.iaqi?.[key] }))
      .filter(e => e.val !== null && e.val !== undefined);
  }

  formatVal(key: string, val: any): string {
    const num = typeof val === 'number' ? val.toFixed(1) : val;
    const unit = (key === 'pm25' || key === 'pm10') ? ' μg/m³' : ' ppb';
    const dot = this.dom === key ? ' ●' : '';
    return `${num}${unit}${dot}`;
  }

  aqiColor(v: number): string { return aqiInfo(v).col; }
}

<div *ngIf="countryCode" class="panel" [style.border-left]="'2px solid ' + (info?.col || '#0d2a4a')">
  <span class="close" (click)="closePanel.emit()">✕</span>

  <div class="sec-label">Selected Region</div>
  <div *ngIf="loading" class="loading">Loading...</div>

  <ng-container *ngIf="detail && info">
    <div class="country-name">{{ detail.countryName || detail.name }}</div>
    <div *ngIf="detail.city" class="city">{{ detail.city }}</div>

    <!-- AQI + trend -->
    <div class="aqi-row">
      <div class="aqi-val" [style.color]="info.col">{{ aqiValue }}</div>
      <div *ngIf="trend" class="trend-block">
        <div class="trend-arrow" [style.color]="trend.trend.color">{{ trend.trend.arrow }}</div>
        <div class="trend-label" [style.color]="trend.trend.color">{{ trend.trend.label }}</div>
      </div>
    </div>
    <div class="aqi-cat" [style.color]="info.col">{{ info.cat }}</div>
    <div *ngIf="srcTag" class="src-tag">{{ srcTag.icon }} {{ srcTag.tag }}</div>

    <!-- Sparkline + forecast -->
    <ng-container *ngIf="spark.length > 1">
      <hr class="divider"/>
      <div class="sec-label">History + 6h Forecast</div>
      <svg [attr.width]="SW" [attr.height]="SH" class="spark-svg">
        <polyline [attr.points]="sparkPoints()" fill="none" [attr.stroke]="info.col" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        <polyline *ngIf="preds.length > 0" [attr.points]="forecastPoints()" fill="none" [attr.stroke]="info.col" stroke-width="1" stroke-dasharray="3 3" opacity="0.6"/>
        <line [attr.x1]="SW*0.65" y1="0" [attr.x2]="SW*0.65" [attr.y2]="SH" stroke="#0d2a4a" stroke-width="1" stroke-dasharray="2 2"/>
        <text [attr.x]="SW*0.67" y="9" class="forecast-label">forecast →</text>
      </svg>

      <div *ngIf="trend" class="pred-row">
        <div class="pred-box" *ngFor="let item of [['1h', trend.predictedIn1h], ['3h', trend.predictedIn3h], ['6h', trend.predictedIn6h]]">
          <div class="pred-lbl">{{ item[0] }}</div>
          <div class="pred-val" [style.color]="aqiColor(+item[1])">{{ item[1] }}</div>
        </div>
      </div>
    </ng-container>

    <!-- Health advisory -->
    <hr class="divider"/>
    <div class="sec-label">Health Advisory</div>
    <div class="row"><span>Healthy adults</span><span class="val">{{ safeTime.healthy }}</span></div>
    <div class="row"><span>Sensitive groups</span><span class="val">{{ safeTime.sensitive }}</span></div>
    <div class="row"><span>Children / Elderly</span>
      <span class="val" [style.color]="safeTime.children === 'Stay in' ? '#ff0000' : '#8ba4c8'">{{ safeTime.children }}</span>
    </div>
    <div class="row"><span>Best time outside</span><span class="val small">{{ bestHour }}</span></div>
    <div class="row"><span>Mask</span>
      <span class="val" [style.color]="mask.needed ? '#ff7e00' : '#00e400'">{{ mask.type }}</span>
    </div>
    <div *ngIf="mask.needed" class="mask-note">{{ mask.note }}</div>

    <!-- Pollutants -->
    <hr class="divider"/>
    <div class="sec-label">Pollutant Readings</div>
    <div class="row" *ngFor="let e of pollutantEntries()">
      <span>{{ e.label }}</span>
      <span class="val" [style.color]="dom === e.key ? info.col : '#8ba4c8'">{{ formatVal(e.key, e.val) }}</span>
    </div>

    <!-- Primary concern -->
    <ng-container *ngIf="polEff">
      <hr class="divider"/>
      <div class="sec-label">Primary Concern</div>
      <div class="concern-card" [style.border-left]="'2px solid ' + polEff.color">
        <div class="concern-label" [style.color]="polEff.color">{{ polEff.label }}</div>
        <div class="concern-source">Source: {{ polEff.source }}</div>
        <div class="concern-effect">{{ polEff.effect }}</div>
      </div>
    </ng-container>

    <hr class="divider"/>
    <div class="advice">{{ info.advice }}</div>

    <div *ngIf="detail.baseline30" class="baseline">
      30-day avg: <span [style.color]="aqiColor(detail.baseline30)">{{ detail.baseline30 }}</span>
      <span *ngIf="(aqiValue ?? 0) > detail.baseline30 * 1.5" class="above"> ↑ above normal</span>
      <span *ngIf="(aqiValue ?? 0) < detail.baseline30 * 0.7" class="below"> ↓ better than usual</span>
    </div>
  </ng-container>
</div>
