// client/src/App.jsx
import { useEffect, useState, useRef } from 'react';
import Globe from './components/Globe';
import InfoPanel from './components/InfoPanel';
import AnomalyFeed from './components/AnomalyFeed';
import { aqiInfo } from './utils/aqi';
import './App.css';

const REFRESH = 15 * 60 * 1000;

export default function App() {
  const [aqiData,       setAqiData]       = useState({});
  const [selectedCode,  setSelectedCode]  = useState(null);
  const [lastUpdated,   setLastUpdated]   = useState(null);
  const [loading,       setLoading]       = useState(true);
  const [error,         setError]         = useState(null);
  const tickerRef = useRef(null);

  async function loadWorld() {
    try {
      const res  = await fetch('/api/aqi/world');
      const json = await res.json();
      if (json.error) throw new Error(json.error);
      setAqiData(json.countries || {});
      setLastUpdated(new Date(json.fetchedAt));
      setLoading(false); setError(null);
    } catch (e) { setError(e.message); setLoading(false); }
  }

  useEffect(() => {
    loadWorld();
    const iv = setInterval(loadWorld, REFRESH);
    return () => clearInterval(iv);
  }, []);

  useEffect(() => {
    if (!tickerRef.current || !Object.keys(aqiData).length) return;
    const sorted = Object.entries(aqiData)
      .filter(([, d]) => d.avgAqi != null)
      .sort(([, a], [, b]) => (b.avgAqi || 0) - (a.avgAqi || 0));
    const items = sorted.map(([code, d]) => {
      const info = aqiInfo(d.avgAqi);
      return `<span style="color:${info.col}">${d.name || code}&nbsp;${d.avgAqi}</span>`;
    }).join('&ensp;·&ensp;');
    tickerRef.current.innerHTML = items + '&ensp;·&ensp;' + items;
  }, [aqiData]);

  const vals      = Object.values(aqiData).map(d => d.avgAqi).filter(Boolean);
  const globalAvg = vals.length ? (vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(1) : '—';
  const globalInfo = aqiInfo(parseFloat(globalAvg));

  return (
    <div className="app">
      <StarField />
      <div className="scanlines" />

      {loading && <div className="loading-screen"><div className="loading-text">Initializing AQI Monitor</div></div>}
      {error    && <div className="error-banner">{error} — retrying...</div>}

      <Globe aqiData={aqiData} onCountryClick={setSelectedCode} selectedCode={selectedCode} />

      {/* Header */}
      <div className="header">
        <div className="brand-label">Global Air Quality</div>
        <div className="brand-title">AirVision<br/>Global</div>
        <div className="brand-sub">v1.0 · MERN Stack</div>
      </div>

      {/* Top right */}
      <div className="top-right">
        <div className="gai-label">Global Avg AQI</div>
        <div className="gai-value" style={{ color: globalInfo.col }}>{globalAvg}</div>
        <div className="gai-status" style={{ color: globalInfo.col }}>
          <span className="live-dot" />LIVE · {vals.length} countries
        </div>
        {lastUpdated && <div className="gai-time">Updated {lastUpdated.toLocaleTimeString()}</div>}
      </div>

      {/* Legend */}
      <div className="legend">
        <div className="leg-title">AQI Level</div>
        {[
          ['#00e400', 'Good ≤50'],
          ['#ffff00', 'Moderate 51–100'],
          ['#ff7e00', 'Sensitive 101–150'],
          ['#ff0000', 'Unhealthy 151–200'],
          ['#8f3f97', 'Very Unhealthy 201–300'],
          ['#7e0023', 'Hazardous >300'],
        ].map(([col, label]) => (
          <div className="leg-item" key={col}>
            <div className="leg-swatch" style={{ background: col }} />{label}
          </div>
        ))}
      </div>

      {/* Anomaly feed (center top) */}
      <AnomalyFeed onCountryClick={setSelectedCode} />

      {/* Country detail panel */}
      <InfoPanel countryCode={selectedCode} onClose={() => setSelectedCode(null)} />

      <div className="hint">Scroll to zoom · names appear when zoomed · click any country</div>

      {/* Ticker */}
      <div className="ticker">
        <div className="ticker-label">AQI Feed</div>
        <div className="ticker-track"><div className="ticker-inner" ref={tickerRef} /></div>
      </div>
    </div>
  );
}

function StarField() {
  const ref = useRef(null);
  useEffect(() => {
    const c = ref.current;
    c.width = window.innerWidth; c.height = window.innerHeight;
    const ctx = c.getContext('2d');
    ctx.fillStyle = '#020510'; ctx.fillRect(0, 0, c.width, c.height);
    for (let i = 0; i < 900; i++) {
      ctx.beginPath();
      ctx.arc(Math.random() * c.width, Math.random() * c.height, Math.random() * 1.1, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(${180 + Math.random()*40},${195 + Math.random()*30},255,${0.15 + Math.random()*0.6})`;
      ctx.fill();
    }
  }, []);
  return <canvas ref={ref} style={{ position: 'fixed', top: 0, left: 0, zIndex: 0, pointerEvents: 'none' }} />;
}

// client-ng/src/app/app.component.ts
import {
  Component, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewInit, HostListener
} from '@angular/core';
import { CommonModule } from '@angular/common';

import { AqiService } from './services/aqi.service';
import { GlobeComponent } from './components/globe/globe.component';
import { InfoPanelComponent } from './components/info-panel/info-panel.component';
import { AnomalyFeedComponent } from './components/anomaly-feed/anomaly-feed.component';
import { aqiInfo } from './utils/aqi';

const REFRESH = 15 * 60 * 1000;

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, GlobeComponent, InfoPanelComponent, AnomalyFeedComponent],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit, OnDestroy, AfterViewInit {
  @ViewChild('starCanvas', { static: true }) starRef!: ElementRef<HTMLCanvasElement>;
  @ViewChild('tickerInner', { static: false }) tickerRef!: ElementRef<HTMLDivElement>;

  aqiData: Record<string, any> = {};
  selectedCode: string | null = null;
  focusCountry: string | null = null;
  lastUpdated: Date | null = null;
  loading = true;
  error: string | null = null;

  readonly legend = [
    { col: '#00e400', label: 'Good ≤50' },
    { col: '#ffff00', label: 'Moderate 51–100' },
    { col: '#ff7e00', label: 'Sensitive 101–150' },
    { col: '#ff0000', label: 'Unhealthy 151–200' },
    { col: '#8f3f97', label: 'Very Unhealthy 201–300' },
    { col: '#7e0023', label: 'Hazardous >300' },
  ];

  private intervalId: any;

  constructor(private aqi: AqiService) {}

  ngOnInit(): void {
    this.loadWorld();
    this.intervalId = setInterval(() => this.loadWorld(), REFRESH);
  }

  ngAfterViewInit(): void {
    this.drawStarfield();
  }

  @HostListener('document:keydown.escape', ['$event'])
  onEsc(e: KeyboardEvent) { this.onClose(); }

  ngOnDestroy(): void { clearInterval(this.intervalId); }

  loadWorld(): void {
    this.aqi.getWorld().subscribe({
      next: (json) => {
        if (json.error) { this.error = json.error; this.loading = false; return; }
        this.aqiData = json.countries || {};
        this.lastUpdated = new Date(json.fetchedAt);
        this.loading = false; this.error = null;
        setTimeout(() => this.updateTicker(), 100);
      },
      error: (e) => { this.error = e.message; this.loading = false; }
    });
  }

  get globalVals(): number[] {
    return Object.values(this.aqiData).map((d: any) => d.avgAqi).filter(Boolean);
  }
  get globalAvg(): string {
    const v = this.globalVals;
    return v.length ? (v.reduce((a, b) => a + b, 0) / v.length).toFixed(1) : '—';
  }
  get globalInfo() { return aqiInfo(parseFloat(this.globalAvg)); }

  onCountryClick(code: string): void { this.selectedCode = code; }
  onClose(): void { this.selectedCode = null; }

  onAnomalyZoom(code: string): void {
    this.selectedCode = code;
    this.focusCountry = null;
    setTimeout(() => { this.focusCountry = code; });
  }

  private drawStarfield(): void {
    const c = this.starRef.nativeElement;
    c.width  = window.innerWidth;
    c.height = window.innerHeight;
    const ctx = c.getContext('2d')!;
    ctx.fillStyle = '#020510'; ctx.fillRect(0, 0, c.width, c.height);
    for (let i = 0; i < 900; i++) {
      ctx.beginPath();
      ctx.arc(Math.random() * c.width, Math.random() * c.height, Math.random() * 1.1, 0, Math.PI * 2);
      ctx.fillStyle = `rgba(${180 + Math.random()*40},${195 + Math.random()*30},255,${0.15 + Math.random()*0.6})`;
      ctx.fill();
    }
  }

  private updateTicker(): void {
    const el = this.tickerRef?.nativeElement;
    if (!el || !Object.keys(this.aqiData).length) return;
    const sorted = Object.entries(this.aqiData)
      .filter(([, d]: any) => d.avgAqi != null)
      .sort(([, a]: any, [, b]: any) => (b.avgAqi || 0) - (a.avgAqi || 0));
    const items = sorted.map(([code, d]: any) => {
      const info = aqiInfo(d.avgAqi);
      return `<span style="color:${info.col}">${d.name || code}&nbsp;${d.avgAqi}</span>`;
    }).join('&ensp;·&ensp;');
    el.innerHTML = items + '&ensp;·&ensp;' + items;
  }
}

<canvas #starCanvas class="starfield"></canvas>
<div class="scanlines"></div>

<div *ngIf="loading" class="loading-screen">
  <div class="loading-text">Initialising AirVision Global…</div>
</div>
<div *ngIf="error" class="error-banner">⚠ {{ error }}</div>

<!-- Globe -->
<app-globe
  [aqiData]="aqiData"
  [selectedCode]="selectedCode"
  [focusCountry]="focusCountry"
  (countryClick)="onCountryClick($event)">
</app-globe>

<!-- Top-left brand -->
<div class="header">
  <div class="brand-label">Real-time Air Quality</div>
  <div class="brand-title">AirVision<br>Global</div>
  <div class="brand-sub">Live AQI Monitor</div>
</div>

<!-- Top-right: global AQI + anomalies stacked below -->
<div class="top-right">
  <div class="gai-label">Global AQI Avg</div>
  <div class="gai-value" [style.color]="globalInfo.col">{{ globalAvg }}</div>
  <div class="gai-status" [style.color]="globalInfo.col">{{ globalInfo.cat }}</div>
  <div *ngIf="lastUpdated" class="gai-time">
    <span class="live-dot"></span>{{ lastUpdated | date:'HH:mm' }} UTC
  </div>
</div>

<!-- Anomaly feed (button positioned top-right below global AQI via CSS) -->
<app-anomaly-feed
  (countryClick)="onCountryClick($event)"
  (zoomTo)="onAnomalyZoom($event)">
</app-anomaly-feed>

<!-- Info panel -->
<app-info-panel
  *ngIf="selectedCode"
  [countryCode]="selectedCode"
  (closePanel)="onClose()">
</app-info-panel>

<!-- AQI legend -->
<div class="legend">
  <div class="leg-title">AQI Level</div>
  <div *ngFor="let l of legend" class="leg-item">
    <span class="leg-swatch" [style.background]="l.col"></span>
    {{ l.label }}
  </div>
</div>

<div class="hint">Drag to rotate · Scroll to zoom · Click country for details</div>

<!-- Ticker -->
<div class="ticker">
  <span class="ticker-label">AQI Feed</span>
  <div class="ticker-track">
    <div #tickerInner class="ticker-inner"></div>
  </div>
</div>
